### ISSUE TITLE
Filebeat Cannot Read Docker Logs

### ISSUE THREAD

**Issue by nkuruvil** [moryachok/elasticstack-lab#1]
Hello, I am attempting to use elasticstack-lab to read and manage logs from my docker containers. When testing on the sample-log given in the git clone, it works fine. However, attempting to connect the filebeat to the docker container logs has proven fruitless. Here is the current code for the filebeat.yml file:

filebeat.yml:
```
filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log
output.logstash:
  hosts: ["logstash:5044"]
```
I expected the filebeat to read the docker files from /var/lib/containers/*/*log and display them up to the Kibana. While Kibana works properly, it does not show any of the docker logs.

I have attempted numerous solutions suggested by google search. Since you created this Elasticstack code, do you have any solutions to link the filebeat to the docker logs?
